import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import "../../app/globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

import { CartProvider } from "@/context/CartContext";

const raleway = Raleway({
  variable: "--font-raleway",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function PublictLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${raleway.variable} antialiased`}>
        <CartProvider>
          <div className="min-h-screen flex flex-col">
            <Navbar />

            <main className="flex-1">
              <div className="mx-auto w-full max-w-7xl px-4">{children}</div>
            </main>

            <Footer />
          </div>
        </CartProvider>
      </body>
    </html>
  );
}
